source "http://rubygems.org"

gem "sinatra"
gem "sinatra-reloader", "~> 1.0"
gem "sinatra-contrib", "~> 1.4.2"
gem 'sinatra-partial', "~> 0.4.0"

group :test, :develop do
  gem 'rake', :require => false
  gem 'rspec', :require => false
end
